# Generated by Django 4.0.1 on 2022-05-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0002_remove_products_quantity_alter_cart_product_qty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
