# Generated by Django 4.0.1 on 2022-05-05 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0003_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='kritunga_cart',
        ),
    ]
