# Generated by Django 4.0.1 on 2022-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0006_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
