# Generated by Django 4.0.1 on 2022-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0007_alter_orderitem_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
