# Generated by Django 4.0.1 on 2022-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0008_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='checkout_status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
