# Generated by Django 4.0.1 on 2022-05-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0010_products_available_alter_chef_chef_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='product',
            field=models.ManyToManyField(to='kritunga.Products'),
        ),
    ]
