# Generated by Django 4.0.1 on 2022-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0011_alter_location_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='available',
        ),
        migrations.AddField(
            model_name='location',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
