# Generated by Django 4.0.1 on 2022-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0012_remove_products_available_location_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='available',
        ),
        migrations.AddField(
            model_name='location',
            name='avail',
            field=models.ManyToManyField(to='kritunga.product_available'),
        ),
    ]
