# Generated by Django 4.0.1 on 2022-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0013_product_available_remove_location_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='avail',
        ),
        migrations.AddField(
            model_name='location',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='product_available',
        ),
    ]
