# Generated by Django 4.0.1 on 2022-05-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0014_remove_location_avail_location_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
